=== nightwisper/ACIT-4850-Assignment-1/instructor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="instructors" type="instructorsType"/>
  <xs:complexType name="timesType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="start" use="optional"/>
        <xs:attribute type="xs:string" name="end" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="datesType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="start" use="optional"/>
        <xs:attribute type="xs:string" name="end" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="courseType">
    <xs:sequence>
      <xs:element name="day">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Mon"/>
            <xs:enumeration value="Tue"/>
            <xs:enumeration value="Wed"/>
            <xs:enumeration value="Thu"/>
            <xs:enumeration value="Fri"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="type"/>
      <xs:element type="timesType" name="times"/>
      <xs:element type="datesType" name="dates"/>
      <xs:element type="xs:string" name="max"/>
      <xs:element name="act">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="hrs"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="crn" use="optional"/>
  </xs:complexType>
  <xs:complexType name="instructorType">
    <xs:sequence>
      <xs:element type="courseType" name="course" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="instructorsType">
    <xs:sequence>
      <xs:element type="instructorType" name="instructor" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== nightwisper/ACIT-4850-Assignment-1/instructor.xml
<?xml version="1.0"?>
<instructors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation='instructor.xsd'><instructor name=" Zhang, Lei"><course crn="44279">
                        <day>Fri</day>
                        <name>ACIT1420</name>
                        <type>A</type>
                        <times start="830" end="1120"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>25</act>
                        <hrs>2.83</hrs>
                    </course><course crn="44280">
                        <day>Wed</day>
                        <name>ACIT1420</name>
                        <type>A</type>
                        <times start="1130" end="1420"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>24</act>
                        <hrs>2.83</hrs>
                    </course><course crn="44946">
                        <day>Tue</day>
                        <name>ACIT1420</name>
                        <type>A</type>
                        <times start="1330" end="1620"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>25</act>
                        <hrs>2.83</hrs>
                    </course><course crn="45155">
                        <day>Mon</day>
                        <name>ACIT3420</name>
                        <type>A</type>
                        <times start="830" end="1120"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>24</act>
                        <hrs>2.83</hrs>
                    </course><course crn="45156">
                        <day>Mon</day>
                        <name>ACIT3420</name>
                        <type>A</type>
                        <times start="1330" end="1620"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>20</act>
                        <hrs>2.83</hrs>
                    </course></instructor><instructor name=" Lane, Thomas F"><course crn="34319">
                        <day>Mon</day>
                        <name>ACIT1515</name>
                        <type>A</type>
                        <times start="1330" end="1620"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>25</act>
                        <hrs>2.83</hrs>
                    </course><course crn="34320">
                        <day>Fri</day>
                        <name>ACIT1515</name>
                        <type>A</type>
                        <times start="1330" end="1620"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>25</act>
                        <hrs>2.83</hrs>
                    </course><course crn="41869">
                        <day>Mon</day>
                        <name>ACIT1515</name>
                        <type>A</type>
                        <times start="830" end="1120"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>26</act>
                        <hrs>2.83</hrs>
                    </course><course crn="44954">
                        <day>Thu</day>
                        <name>ACIT2620</name>
                        <type>A</type>
                        <times start="1330" end="1620"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>22</act>
                        <hrs>2.83</hrs>
                    </course><course crn="44955">
                        <day>Thu</day>
                        <name>ACIT2620</name>
                        <type>A</type>
                        <times start="830" end="1120"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>13</act>
                        <hrs>2.83</hrs>
                    </course></instructor><instructor name=" Hart, Richard"><course crn="34322">
                        <day>Wed</day>
                        <name>ACIT1620</name>
                        <type>A</type>
                        <times start="830" end="1120"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>25</act>
                        <hrs>2.83</hrs>
                    </course><course crn="34323">
                        <day>Tue</day>
                        <name>ACIT1620</name>
                        <type>A</type>
                        <times start="830" end="1120"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>25</act>
                        <hrs>2.83</hrs>
                    </course><course crn="41870">
                        <day>Thu</day>
                        <name>ACIT1620</name>
                        <type>A</type>
                        <times start="830" end="1120"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>25</act>
                        <hrs>2.83</hrs>
                    </course><course crn="39753">
                        <day>Tue</day>
                        <name>COMP3130</name>
                        <type>L</type>
                        <times start="1330" end="1420"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>19</act>
                        <hrs>0.83</hrs>
                    </course><course crn="39754">
                        <day>Tue</day>
                        <name>COMP3130</name>
                        <type>A</type>
                        <times start="1430" end="1620"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>19</act>
                        <hrs>1.83</hrs>
                    </course><course crn="41830">
                        <day>Mon</day>
                        <name>COMP3130</name>
                        <type>L</type>
                        <times start="1330" end="1420"></times>
                        <dates start="04 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>20</act>
                        <hrs>0.83</hrs>
                    </course><course crn="41831">
                        <day>Mon</day>
                        <name>COMP3130</name>
                        <type>A</type>
                        <times start="1430" end="1620"></times>
                        <dates start="04 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>20</act>
                        <hrs>1.83</hrs>
                    </course><course crn="41320">
                        <day>Thu</day>
                        <name>COMP1620</name>
                        <type>L</type>
                        <times start="1430" end="1520"></times>
                        <dates start="04 Sep 2018" end="07 Dec 2018"></dates>
                        <max>23</max>
                        <act>20</act>
                        <hrs>0.83</hrs>
                    </course><course crn="41321">
                        <day>Thu</day>
                        <name>COMP1620</name>
                        <type>A</type>
                        <times start="1230" end="1420"></times>
                        <dates start="04 Sep 2018" end="07 Dec 2018"></dates>
                        <max>23</max>
                        <act>20</act>
                        <hrs>1.83</hrs>
                    </course></instructor><instructor name=" Yu, Benjamin"><course crn="34355">
                        <day>Thu</day>
                        <name>ACIT1630</name>
                        <type>A</type>
                        <times start="830" end="1120"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>25</act>
                        <hrs>2.83</hrs>
                    </course><course crn="34356">
                        <day>Thu</day>
                        <name>ACIT1630</name>
                        <type>A</type>
                        <times start="1330" end="1620"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>25</act>
                        <hrs>2.83</hrs>
                    </course><course crn="41871">
                        <day>Fri</day>
                        <name>ACIT1630</name>
                        <type>A</type>
                        <times start="830" end="1120"></times>
                        <dates start="05 Sep 2018" end="07 Dec 2018"></dates>
                        <max>25</max>
                        <act>25</act>
                        <hrs>2.83</hrs>
                    </course><course crn="35504">
                        <day>Mon</day>
                        <name>COMP4921</name>
                        <type>L</type>
